include ../Make.defines

PROGS = tcpcliselect01 tcpcliselect02 tcpservselect01\
		tcpservpoll tcpservshut tcpclishut

TEST = tcpcli01 rlimit

all: ${PROGS} ${TEST}

clean:
	rm -f ${PROGS} ${CLEANFILES}
