include ../Make.defines

PROGS = hostent servname daytimetcpcli1 daytimetcpcli\
		daytimetcpsrv1 daytimetcpsrv2\
		daytimeudpcli1 daytimeudpsrv2

TEST = testga getopt getproto hostent2 daytimetcpcli2\
	   daytimetcpcli3

all: ${PROGS} ${TEST}

clean:
	rm -f ${PROGS} ${TEST}
