include ../Make.defines

PROGS = tcpserv01 tcpcli01 tcpcli04 tcpserv04\
		tcpcli01_pipe tcpserv05 tcpcli06 tcpserv06\

TEST = sigblock sigsus tcpclipipe endian

all: ${PROGS} ${TEST}

clean:
	rm -f ${PROGS} ${CLEANFILES}
