include ../Make.defines

PROGS = udpserv01 udpcli01 udpcli_connect\
		udpservloop udpcliloop udpservloop1\
		udpcli_if udpservselect

TEST = udpclibig udpservbig

all: ${PROGS} ${TEST}

clean:
	rm -f ${PROGS} ${TEST}
